In [1]:
import numpy as np
import cmath
import math
import sympy as sp
from scipy.optimize import minimize
import matplotlib.pyplot as plt

### Oefening 2
Bereken op een efficiënte manier (zonder lussen) de som van de eerste honderd kwadraten $1^2 + 2^2 + \dots + 100^2$.

In [2]:
v = np.arange(1,101)
v2 = v**2
print(np.sum(v2))

338350


### Oefening 4
Stel $z = \sqrt{2} e^{3j\pi/5}$. Bepaal het reëel en imaginair deel. Bepaal (in graden) het argument (=poolhoek) van het complex toegevoegde van $(z+1)$.

In [3]:
z=math.sqrt(2)*cmath.exp(3j*math.pi/5)
print("Het reëel deel van z is: ", z.real, "en het imaginair deel is: ", z.imag)

z1 = (z+1).conjugate()
print("De poolhoek is: ", math.degrees(cmath.phase(z1)))

Het reëel deel van z is:  -0.437016024448821 en het imaginair deel is:  1.3449970239279148
De poolhoek is:  -67.28696631637692


### Oefening 5
Voer op de meest handige manier de matrix $A = \begin{pmatrix} 1 & 3 & 5 & 7 & 9 & \dots & 45 & 47 \\ 1 & 3 & 5 & 7 & 9 & \dots & 45 & 47 \\ 1 & 3 & 5 & 7 & 9 & \dots & 45 & 47 \\ \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\ 1 & 3 & 5 & 7 & 9 & \dots & 45 & 47 \end{pmatrix}$ in die 18 rijen bevat.

In [4]:
v = np.arange(1,48,2)
A = np.tile(v,(18,1))

print(A)

[[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]
 [ 1  3  5  7  9 11 13 15

### Oefening 8
Bereken m.b.v. vectoren de oppervlakte van de driehoek met hoekpunten $a(1, 2, 0)$, $b(3, 0, -3)$ en $c(5, 2, 6)$.

In [5]:
a = np.array([1,2,0])
b = np.array([3,0,-3])
c = np.array([5,2,6])

ab = b-a
ac = c-a

print(1/2*np.linalg.norm(np.cross(ab,ac)))

14.0


### Oefening 9
Bereken het gemiddelde van de elementen uit de verzameling $\{f(0), f(0.1), \dots, f(1)\}$ met $f(t) = \frac{t}{1 + \sqrt{t}}$.(Werk zonder lussen.)

In [6]:
t = np.linspace(0,1,11)
f = t/(1+np.sqrt(t))
print(np.mean(f))

0.277209136544736
